/*
  Warnings:

  - The values [CERTIFICATE,DIPLOMA,ASSOCIATE_DEGREE,PROFESSIONAL_CERTIFICATION,CERTIFICATION_PROFESSIONNELLE,VOCATIONAL_TRAINING,FORMATION_PROFESSIONNELLE,ONLINE_COURSE,COURS_EN_LIGNE,EXECUTIVE_EDUCATION,EDUCATION_EXECUTIVE,CONTINUING_EDUCATION,FORMATION_CONTINUE,CAP,BEP,GRANDE_ECOLE,CLASSE_PREPA,CPGE] on the enum `ProgramType` will be removed. If these variants are still used in the database, this will fail.
  - The values [PUBLIC_PRIMARY_SCHOOL,PRIVATE_PRIMARY_SCHOOL,PUBLIC_SECONDARY_SCHOOL,PRIVATE_SECONDARY_SCHOOL,INTERNATIONAL_SCHOOL,TECHNICAL_SCHOOL,VOCATIONAL_SCHOOL,COMMUNITY_COLLEGE,POLYTECHNIC,GRANDE_ECOLE,LYCEE_PUBLIC,LYCEE_PRIVE,COLLEGE_PUBLIC,COLLEGE_PRIVE,ECOLE_MATERNELLE,ECOLE_ELEMENTAIRE,UNIVERSITE_PUBLIQUE,UNIVERSITE_PRIVEE,ECOLE_SUPERIEURE,ECOLE_DE_COMMERCE,ECOLE_D_INGENIEURS,ECOLE_DES_ARTS] on the enum `SchoolType` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `currency` on the `SchoolProgram` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ProgramType_new" AS ENUM ('HND', 'BTECH', 'LICENCE', 'LICENCE_PROFESSIONNELLE', 'BACHELORS', 'MASTERS', 'MASTER_PROFESSIONNEL', 'MASTER_RECHERCHE', 'MBA', 'PHD', 'DOCTORAT', 'POSTDOCTORAL', 'POSTDOC', 'BTS', 'DUT', 'DEUG', 'DEUST');
ALTER TABLE "Program" ALTER COLUMN "type" TYPE "ProgramType_new" USING ("type"::text::"ProgramType_new");
ALTER TYPE "ProgramType" RENAME TO "ProgramType_old";
ALTER TYPE "ProgramType_new" RENAME TO "ProgramType";
DROP TYPE "ProgramType_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "SchoolType_new" AS ENUM ('PUBLIC_STATE_UNIVERSITY', 'PRIVATE_UNIVERSITY');
ALTER TABLE "School" ALTER COLUMN "type" TYPE "SchoolType_new" USING ("type"::text::"SchoolType_new");
ALTER TYPE "SchoolType" RENAME TO "SchoolType_old";
ALTER TYPE "SchoolType_new" RENAME TO "SchoolType";
DROP TYPE "SchoolType_old";
COMMIT;

-- AlterTable
ALTER TABLE "SchoolProgram" DROP COLUMN "currency";

-- DropEnum
DROP TYPE "Currency";
